---
layout:  page
title: "Visualizations"
comments:  true
published:  true
author: "Marcin Kosiński"
date: 2016-02-24 00:45:00
categories: [RTCGA]
output:
  html_document:
    mathjax:  default
    fig_caption:  true
---


```{r include=FALSE}
library(knitr)
opts_chunk$set(comment="", message=FALSE, warning = FALSE, 
               tidy.opts=list(keep.blank.line=TRUE, width.cutoff=150),
							 options(width=150), eval = TRUE)
```

```{r}
library(RTCGA)
library(ggplot2)
```


## Biplot of RNASeq - Plot of 2 main componens of Principal Components Analysis

```{r}
## RNASeq expressions
library(RTCGA.rnaseq)
library(dplyr)
expressionsTCGA(BRCA.rnaseq, OV.rnaseq, HNSC.rnaseq) %>%
 	dplyr::rename(cohort = dataset) %>%	
 	filter(substr(bcr_patient_barcode, 14, 15) == "01") -> BRCA.OV.HNSC.rnaseq.cancer
pcaTCGA(BRCA.OV.HNSC.rnaseq.cancer, "cohort") -> pca_plot
plot(pca_plot)
```



## Boxplots of logarithm of MET gene RNASeq expression

```{r}

library(RTCGA.rnaseq)
# perfrom plot
library(dplyr)
expressionsTCGA(
	ACC.rnaseq,
	BLCA.rnaseq,
	BRCA.rnaseq,
	OV.rnaseq,
	extract.cols = "MET|4233"
	) %>%
 	dplyr::rename(
 	cohort = dataset,
 	MET = `MET|4233`
 	) %>%  
 	filter(
 	substr(bcr_patient_barcode, 14, 15) == "01" #cancer samples
 	) -> ACC_BLCA_BRCA_OV.rnaseq
boxplotTCGA(
	ACC_BLCA_BRCA_OV.rnaseq,
	"reorder(cohort,log1p(MET), median)",
	"log1p(MET)",
	xlab = "Cohort Type",
	ylab = "Logarithm of MET",
	legend.title = "Cohorts",
	legend = "bottom"
	) -> boxplot1
plot(boxplot1)
```

### Facet example

```{r}
library(RTCGA.mutations)
library(dplyr)
mutationsTCGA(
	BRCA.mutations,
	OV.mutations,
	ACC.mutations,
	BLCA.mutations
	) %>% 
	filter(Hugo_Symbol == 'TP53') %>%
	filter(substr(bcr_patient_barcode, 14, 15) == "01") %>% # cancer tissue
 	mutate(bcr_patient_barcode = substr(bcr_patient_barcode, 1, 12)) ->
	ACC_BLCA_BRCA_OV.mutations
 
mutationsTCGA(BRCA.mutations, OV.mutations, ACC.mutations, BLCA.mutations) ->
	ACC_BLCA_BRCA_OV.mutations_all
 
 ACC_BLCA_BRCA_OV.rnaseq %>%
 	mutate(bcr_patient_barcode = substr(bcr_patient_barcode, 1, 15)) %>%
 	filter(
 		bcr_patient_barcode %in% 
 		substr(ACC_BLCA_BRCA_OV.mutations_all$bcr_patient_barcode, 1, 15)
 		) %>%
 	# took patients for which we had any mutation information
 	# so avoided patients without any information about mutations
 	mutate(bcr_patient_barcode = substr(bcr_patient_barcode, 1, 12)) %>%
 	# strin_length(ACC_BLCA_BRCA_OV.mutations$bcr_patient_barcode) == 12
 	left_join(
 		ACC_BLCA_BRCA_OV.mutations,
 		by = "bcr_patient_barcode"
 		) %>% #joined only with tumor patients
 	mutate(TP53 = ifelse(!is.na(Variant_Classification), "Mut", "WILD")) %>%
 	select(cohort, MET, TP53) -> ACC_BLCA_BRCA_OV.rnaseq_TP53mutations
 
boxplotTCGA(
	ACC_BLCA_BRCA_OV.rnaseq_TP53mutations,
	"reorder(cohort,log1p(MET), median)",
	"log1p(MET)",
	xlab = "Cohort Type",
	ylab = "Logarithm of MET",
	legend.title = "Cohorts",
	legend = "bottom",
	facet.names = c("TP53")
	) -> boxplo2
plot(boxplo2)
boxplotTCGA(
	ACC_BLCA_BRCA_OV.rnaseq_TP53mutations,
	"reorder(cohort,log1p(MET), median)",
	"log1p(MET)",
	xlab = "Cohort Type",
	ylab = "Logarithm of MET",
	legend.title = "Cohorts",
	legend = "bottom",
	fill = c("TP53")
	) -> boxplot3
plot(boxplot3)
boxplotTCGA(
	ACC_BLCA_BRCA_OV.rnaseq_TP53mutations,
	"reorder(TP53,log1p(MET), median)",
	"log1p(MET)",
	xlab = "Cohort Type",
	ylab = "Logarithm of MET",
	legend.title = "Cohorts",
	legend = "bottom",
	fill = c("cohort")
	) -> boxplot4
plot(boxplot4)
````

## Kaplan-Meier estimates of survival curves for cancer types and mutations in gene TP53

```{r}
library(RTCGA.mutations)
library(dplyr)
library(survminer)
mutationsTCGA(BRCA.mutations, OV.mutations) %>%
 	filter(Hugo_Symbol == 'TP53') %>%
 	filter(substr(bcr_patient_barcode, 14, 15) == "01") %>% # cancer tissue
 	mutate(bcr_patient_barcode = substr(bcr_patient_barcode, 1, 12)) ->
	BRCA_OV.mutations
 
library(RTCGA.clinical)
survivalTCGA(
	BRCA.clinical,
	OV.clinical,
	extract.cols = "admin.disease_code"
	) %>%
 	dplyr::rename(disease = admin.disease_code) -> BRCA_OV.clinical

BRCA_OV.clinical %>%
 	left_join(
 		BRCA_OV.mutations,
 		by = "bcr_patient_barcode"
 		) %>%
 	mutate(TP53 = ifelse(!is.na(Variant_Classification), "Mut","WILDorNOINFO")) ->
	BRCA_OV.clinical_mutations
 
BRCA_OV.clinical_mutations %>%
	select(times, patient.vital_status, disease, TP53) -> BRCA_OV.2plot

kmTCGA(
	BRCA_OV.2plot,
	explanatory.names = c("TP53", "disease"),
	break.time.by = 400,
	xlim = c(0,2000)
	) -> km_plot
print(km_plot)
```

### Kaplan-Meier estimates of survival curves for BRAF gene

```{r}
archivist::aread('MarcinKosinski/coxphSGD/1a06') %>% 
	do.call(rbind, . ) %>%
	kmTCGA(
		explanatory.names = "BRAF",
		break.time.by = 1000,
		xlim = c(0, 5000)
		) -> km_plot2
print(km_plot2)
```



